### PR TITLE
API access

### PR DESCRIPTION
**Pull request by michaelmior**
I was considering writing a crawler to pull some of the collected data, but it would be nicer if there was an API. Would you accept a PR adding an API to get repo data? Probably would use [Django REST Framework](http://www.django-rest-framework.org/) since it's something I'm familiar with and it would make this a pretty quick project.

### CODE REVIEW

**Comment by michaelmior** [comment]
See the attached pull request which adds an API that exposes repository details as well as a way to list repositories with some optional filtering.

**Comment by apavlo** [comment]
@michaelmior This is deployed and live. Try it out.

**Comment by michaelmior** [comment]
Thanks! I just realized however that there's no default limit for the number of repositories that get returned so I believe it's trying to pull the entire database now. See the latest commit I added on the branch for the necessary pagination settings.

**Comment by michaelmior** [comment]
Unfortunately I hit the `/api/repositories/` URL when testing this and the site seems to be slowed so it's possible there's a rogue query that needs to be killed. Sorry about that.

**Comment by apavlo** [comment]
Yeah I restarted apace. Can you send a new PR?

**Comment by michaelmior** [comment]
Done

**Pull request merged**
