### PR TITLE
Add page limit

### PR DESCRIPTION
**Pull request by michaelmior**
Adds page numbering for the API added in #15

### CODE REVIEW

**Comment by apavlo** [comment]
Try it now

**Comment by apavlo** [comment]
It's still eating up a lot of RAM with Apache. This machine only has 4GB. Let me see if I can get them to add more today.

**Comment by michaelmior** [comment]
I see the detail API working correctly (e.g. http://cmdbac.cs.cmu.edu/api/repository/183/info/?format=json). However, things still seem to hang when I try to do the repository listing. I tried locally (albeit with a very small database) and pagination appeared to work correctly so I'm not sure why this would be such an issue. Did you apply the settings to the `settings.py`?

**Comment by apavlo** [comment]
Ah that's what I missed. Sorry, I merged it in a hurry. It should be fixed. Try it again.

**Comment by zeyuanxy** [comment]
@apavlo @michaelmior it works on my side.

**Comment by michaelmior** [comment]
@apavlo Perfect! Works for me now. Thanks again for pushing this out so quickly!

**Comment by apavlo** [comment]
Thanks for implementing it. Send us any other PRs for features that you need and I'll add it in.

**Pull request merged**
